package co.nvqa.common.core.utils;

public interface CoreScenarioStorageKeys {

  String KEY_LIST_OF_CREATED_RESERVATIONS = "KEY_LIST_OF_CREATED_RESERVATIONS";
  String KEY_CORE_LIST_OF_DB_TRACKING_IDS = "KEY_CORE_LIST_OF_DB_TRACKING_IDS";
  String KEY_DESTINATION_HUB_ID = "KEY_DESTINATION_HUB_ID";
  String KEY_LIST_OF_CREATED_ROUTES = "KEY_LIST_OF_CREATED_ROUTES";
  @Deprecated
  String KEY_LIST_OF_CREATED_ROUTE_ID = "KEY_LIST_OF_CREATED_ROUTE_ID";
  @Deprecated
  String KEY_CREATED_ROUTE_ID = "KEY_CREATED_ROUTE_ID";
  String KEY_LIST_OF_CREATED_ORDERS = "KEY_LIST_OF_CREATED_ORDERS";
  String KEY_CORE_LIST_OF_CREATED_ORDERS_CORE_DB = "KEY_CORE_LIST_OF_CREATED_ORDERS_CORE_DB";
  String KEY_LIST_OF_RESERVATION_IDS = "KEY_LIST_OF_RESERVATION_IDS";
  String KEY_CORE_LIST_OF_ORDER_PICKUPS = "KEY_CORE_LIST_OF_ORDER_PICKUPS";
  String KEY_CORE_LIST_OF_INBOUND_SCANS = "KEY_CORE_LIST_OF_INBOUND_SCANS";
  String KEY_LIST_OF_PICKUPS = "KEY_LIST_OF_PICKUPS";
  String KEY_CORE_LIST_OF_ORDER_DETAILS = "KEY_CORE_LIST_OF_ORDER_DETAILS";
  String KEY_CORE_WAYPOINT_DETAILS = "KEY_CORE_WAYPOINT_DETAILS";
  String KEY_CORE_LIST_OF_ORDER_EVENTS = "KEY_CORE_LIST_OF_ORDER_EVENTS";
  String KEY_CORE_LIST_OF_MESSAGING_HISTORY_DATA = "KEY_CORE_LIST_OF_MESSAGING_HISTORY_DATA";

  String KEY_WAYPOINT_ID = "KEY_WAYPOINT_ID";
  String KEY_TRANSACTION_ID = "KEY_TRANSACTION_ID";
  String KEY_CORE_TRANSACTION = "KEY_CORE_TRANSACTION";
  String KEY_CORE_LIST_OF_TRANSACTIONS = "KEY_CORE_LIST_OF_TRANSACTIONS";
  String KEY_LIST_OF_RESERVATIONS = "KEY_LIST_OF_RESERVATIONS";
  String KEY_CORE_LIST_OF_RESERVATIONS_DB = "KEY_CORE_LIST_OF_RESERVATIONS_DB";

  String KEY_SAVED_ORDER_WEIGHT = "KEY_SAVED_ORDER_WEIGHT";
  String KEY_EXPECTED_OLD_WEIGHT = "KEY_EXPECTED_OLD_WEIGHT";
  String KEY_CORE_LIST_OF_CREATED_STAMP_ID = "KEY_CORE_LIST_OF_CREATED_STAMP_ID";

  //  archive & unarchive route response
  String KEY_ROUTE_RESPONSE = "KEY_ROUTE_RESPONSE";

  String KEY_LIST_OF_COVERAGE = "KEY_LIST_OF_COVERAGE";
  String KEY_COVERAGE_ID = "KEY_COVERAGE_ID";
  String KEY_LIST_OF_CREATED_AREAS = "KEY_LIST_OF_CREATED_AREAS";

  String KEY_CORE_MERGE_WAYPOINT_RESPONSE = "KEY_CORE_MERGE_WAYPOINT_RESPONSE";

  String KEY_CORE_WAREHOUSE_SWEEPS = "KEY_CORE_WAREHOUSE_SWEEPS";
  String KEY_CORE_LIST_OF_CREATED_OJS = "KEY_CORE_LIST_OF_CREATED_OJS";
  String KEY_CORE_ROUTE_CASH_INBOUND_COD = "KEY_CORE_ROUTE_CASH_INBOUND_COD";
  String KEY_CORE_COD_GOODS_AMOUNT = "KEY_CORE_COD_GOODS_AMOUNT";
  String KEY_CORE_ROUTE_CASH_INBOUND_COD_EDITED = "KEY_CORE_ROUTE_CASH_INBOUND_COD_EDITED";

  String KEY_CORE_BULK_ROUTE_PA_JOB_RESPONSE = "KEY_CORE_BULK_ROUTE_PA_JOB_RESPONSE";
  String KEY_LIST_OF_CREATED_ROUTE_GROUPS = "KEY_LIST_OF_CREATED_ROUTE_GROUPS";

  String KEY_CORE_LAZADA_3PL_COMMENT = "KEY_CORE_LAZADA_3PL_COMMENT";
  String KEY_CORE_LIST_OF_ORDER_DELIVERY_DETAILS = "KEY_CORE_LIST_OF_ORDER_DELIVERY_DETAILS";

}
