package co.nvqa.common.core.utils;

public interface CoreScenarioStorageKeys {

  String KEY_LIST_OF_CREATED_RESERVATIONS = "KEY_LIST_OF_CREATED_RESERVATIONS";
  String KEY_DESTINATION_HUB_ID = "KEY_DESTINATION_HUB_ID";
  String KEY_LIST_OF_CREATED_ROUTES = "KEY_LIST_OF_CREATED_ROUTES";
  String KEY_LIST_OF_CREATED_ORDERS = "KEY_LIST_OF_CREATED_ORDERS";
  String KEY_LIST_OF_RESERVATION_IDS = "KEY_LIST_OF_RESERVATION_IDS";
  String KEY_LIST_OF_PICKUPS = "KEY_LIST_OF_PICKUPS";

  String KEY_WAYPOINT_ID = "KEY_WAYPOINT_ID";
  String KEY_LIST_OF_RESERVATIONS = "KEY_LIST_OF_RESERVATIONS";
}
