package co.nvqa.common.core.utils;

public interface CoreScenarioStorageKeys {

  String KEY_CREATED_ADDRESS = "KEY_CREATED_ADDRESS";
  String KEY_LIST_OF_CREATED_RESERVATIONS = "KEY_LIST_OF_CREATED_RESERVATIONS";
  String KEY_DESTINATION_HUB_ID = "KEY_DESTINATION_HUB_ID";
  String KEY_LIST_OF_CREATED_ROUTES = "KEY_LIST_OF_CREATED_ROUTES";
  String KEY_LIST_OF_CREATED_ORDERS = "KEY_LIST_OF_CREATED_ORDERS";
  String KEY_LIST_OF_CREATED_PP_ORDER = "KEY_LIST_OF_CREATED_PP_ORDER";
  String KEY_LIST_OF_CREATED_DD_ORDER = "KEY_LIST_OF_CREATED_DD_ORDER";

}
